Repository SaintZet/DayzMapsLoader, pull requests merged in 2023-05, with the labels that each got.

#67 Transfer webp library files to Webp directory.
  src/DayzMapsLoader.Application/DayzMapsLoader.Application.csproj
  src/DayzMapsLoader.Application/Helpers/WebpDecoder/WebP.cs
  src/DayzMapsLoader.Application/Helpers/WebpDecoder/libwebp_x64.dll
  src/DayzMapsLoader.Application/Helpers/WebpDecoder/libwebp_x86.dll
Labels: architecture

#69 Swap horizontal and vertical numbers in name files.
  src/DayzMapsLoader.Application/Services/MapDownloadArchiveService.cs
Labels: bug

#68 Add summary and produces responce types.
  src/DayzMapsLoader.Presentation.WebApi/Controllers/DownloadMapController.cs
Labels: documentation

#74 Correct, add new unit and intagration tests
  src/DayzMapsLoader.Application.Tests.xUnit/DayzMapsLoader.Application.Tests.xUnit.csproj
  src/DayzMapsLoader.Application.Tests.xUnit/ServicesTests/MapDownloadArchiveServiceTests.cs
  src/DayzMapsLoader.Application.Tests.xUnit/ServicesTests/MapDownloadImageServiceTests.cs
  src/DayzMapsLoader.Application.Tests.xUnit/ServicesTests/MapMergeServiceTests.cs
  src/DayzMapsLoader.Application.Tests.xUnit/TestData/MapDownload/DataGenerator.cs
  src/DayzMapsLoader.Application.Tests.xUnit/TestData/MapMerge/jpg/0,0.jpg
  src/DayzMapsLoader.Application.Tests.xUnit/TestData/MapMerge/jpg/0,1.jpg
  src/DayzMapsLoader.Application.Tests.xUnit/TestData/MapMerge/jpg/1,0.jpg
  src/DayzMapsLoader.Application.Tests.xUnit/TestData/MapMerge/jpg/1,1.jpg
  src/DayzMapsLoader.Application.Tests.xUnit/TestData/MapMerge/jpg/Original.jpg
  src/DayzMapsLoader.Application.Tests.xUnit/TestData/MapMerge/png/0,0.png
  src/DayzMapsLoader.Application.Tests.xUnit/TestData/MapMerge/png/0,1.png
  src/DayzMapsLoader.Application.Tests.xUnit/TestData/MapMerge/png/1,0.png
  src/DayzMapsLoader.Application.Tests.xUnit/TestData/MapMerge/png/1,1.png
  src/DayzMapsLoader.Application.Tests.xUnit/TestData/MapMerge/png/Original.png
  src/DayzMapsLoader.Application.Tests.xUnit/TestData/MapMerge/webp/0,0.webp
  src/DayzMapsLoader.Application.Tests.xUnit/TestData/MapMerge/webp/0,1.webp
  src/DayzMapsLoader.Application.Tests.xUnit/TestData/MapMerge/webp/1,0.webp
  src/DayzMapsLoader.Application.Tests.xUnit/TestData/MapMerge/webp/1,1.webp
  src/DayzMapsLoader.Application.Tests.xUnit/TestData/MapMerge/webp/Original.webp
  src/DayzMapsLoader.Application.Tests.xUnit/Usings.cs
  src/DayzMapsLoader.Application.UnitTests/DayzMapsLoader.Application.UnitTests.csproj
  src/DayzMapsLoader.Application.UnitTests/Managers/ImageMergerTest.cs
  src/DayzMapsLoader.Application.UnitTests/Services/MapDownloaderTest.cs
  src/DayzMapsLoader.Application/Abstractions/Services/IMapDownloadImageService.cs
  src/DayzMapsLoader.Application/DayzMapsLoader.Application.csproj
  src/DayzMapsLoader.Application/Services/MapDownloadImageService.cs
  src/DayzMapsLoader.Application/Services/MapMergeService.cs
  src/DayzMapsLoader.Infrastructure/Extensions/ServiceCollectionExtensions.cs
  src/DayzMapsLoader.Infrastructure/Services/MultipleThirdPartyApiService.cs
  src/DayzMapsLoader.Presentation.WebApi/DayzMapsLoader.Presentation.WebApi.csproj
  src/DayzMapsLoader.Presentation.WebApi/Extensions/ServiceCollectionExtensions.cs
  src/DayzMapsLoader.Presentation.WebApi/Startup.cs
  src/DayzMapsLoader.Shared/Wrappers/MapParts.cs
  src/DayzMapsLoader.Shared/Wrappers/MapSize.cs
  src/DayzMapsLoader.sln
Labels: refactoring, development, architecture

#76 Change signature AddDatabase extension method.
  src/DayzMapsLoader.Application.Tests.xUnit/ServicesTests/MapDownloadArchiveServiceTests.cs
  src/DayzMapsLoader.Application.Tests.xUnit/ServicesTests/MapDownloadImageServiceTests.cs
  src/DayzMapsLoader.Infrastructure/Extensions/ServiceCollectionExtensions.cs
  src/DayzMapsLoader.Presentation.WebApi/Startup.cs
Labels: refactoring

#77 Fix DownloadAllMapImagesAsync method. Refactor.
  src/DayzMapsLoader.Application/Services/BaseMapDownloadService.cs
  src/DayzMapsLoader.Application/Services/MapDownloadImageService.cs
Labels: bug, refactoring

#85 Move FileService to Infrastructure. Create DependencyInjection project.
  src/DayzMapsLoader.Core.Tests.xUnit/DayzMapsLoader.Core.Tests.xUnit.csproj
  src/DayzMapsLoader.Core.Tests.xUnit/ServicesTests/MapDownloadArchiveServiceTests.cs
  src/DayzMapsLoader.Core.Tests.xUnit/ServicesTests/MapDownloadImageServiceTests.cs
  src/DayzMapsLoader.Core/Contracts/Infrastructure/Services/IFileService.cs
  src/DayzMapsLoader.Core/Extensions/ServiceCollectionExtensions.cs
  src/DayzMapsLoader.DependencyInjection/DayzMapsLoader.DependencyInjection.csproj
  src/DayzMapsLoader.DependencyInjection/ServiceCollectionExtensions.cs
  src/DayzMapsLoader.Infrastructure/DayzMapsLoader.Infrastructure.csproj
  src/DayzMapsLoader.Infrastructure/Extensions/ServiceCollectionExtensions.cs
  src/DayzMapsLoader.Infrastructure/Services/FileService.cs
  src/DayzMapsLoader.Presentation.WebApi/DayzMapsLoader.Presentation.WebApi.csproj
  src/DayzMapsLoader.Presentation.WebApi/Startup.cs
  src/DayzMapsLoader.Presentation.Wpf/App.xaml.cs
  src/DayzMapsLoader.Presentation.Wpf/DayzMapsLoader.Presentation.Wpf.csproj
  src/DayzMapsLoader.Presentation.Wpf/Services/PersistAndRestoreService.cs
  src/DayzMapsLoader.Presentation.Wpf/ViewModels/ContentGridMapDetailViewModel.cs
  src/DayzMapsLoader.Presentation.Wpf/ViewModels/ContentGridMapsViewModel.cs
  src/DayzMapsLoader.Presentation.Wpf/ViewModels/ContentGridProvidersViewModel.cs
  src/DayzMapsLoader.Shared/DayzMapsLoader.Shared.csproj
  src/DayzMapsLoader.sln
Labels: architecture

#90 89 Correct test project
  src/DayzMapsLoader.Core.Tests.xUnit/Core/FeaturesTests/MapArchive/Queries/GetAllMapsImagesArchiveTests.cs
  src/DayzMapsLoader.Core.Tests.xUnit/Core/FeaturesTests/MapArchive/Queries/GetMapImageArchiveTest.cs
  src/DayzMapsLoader.Core.Tests.xUnit/Core/FeaturesTests/MapArchive/Queries/GetMapImagePartsArchiveTests.cs
  src/DayzMapsLoader.Core.Tests.xUnit/Core/FeaturesTests/MapProviders/Queries/GetMapProvidersTests.cs
  src/DayzMapsLoader.Core.Tests.xUnit/Core/FeaturesTests/Maps/Queries/GetMapsTests.cs
  src/DayzMapsLoader.Core.Tests.xUnit/Core/FeaturesTests/ProvidedMaps/Queries/GetProvidedMapsByDetailsTests.cs
  src/DayzMapsLoader.Core.Tests.xUnit/Core/FeaturesTests/ProvidedMaps/Queries/GetProvidedMapsByMapIdTests.cs
  src/DayzMapsLoader.Core.Tests.xUnit/Core/FeaturesTests/ProvidedMaps/Queries/GetProvidedMapsByProviderIdTests.cs
  src/DayzMapsLoader.Core.Tests.xUnit/Core/FeaturesTests/ProvidedMaps/Queries/GetProvidedMapsTests.cs
  src/DayzMapsLoader.Core.Tests.xUnit/Core/ServicesTests/MapDownloadArchiveServiceTests.cs
  src/DayzMapsLoader.Core.Tests.xUnit/Core/ServicesTests/MapDownloadImageServiceTests.cs
  src/DayzMapsLoader.Core.Tests.xUnit/Core/ServicesTests/MapMergeServiceTests.cs
  src/DayzMapsLoader.Core.Tests.xUnit/Core/TestData/MapDownload/DataGenerator.cs
  src/DayzMapsLoader.Core.Tests.xUnit/Core/TestData/MapMerge/jpg/0,0.jpg
  src/DayzMapsLoader.Core.Tests.xUnit/Core/TestData/MapMerge/jpg/0,1.jpg
  src/DayzMapsLoader.Core.Tests.xUnit/Core/TestData/MapMerge/jpg/1,0.jpg
  src/DayzMapsLoader.Core.Tests.xUnit/Core/TestData/MapMerge/jpg/1,1.jpg
  src/DayzMapsLoader.Core.Tests.xUnit/Core/TestData/MapMerge/jpg/Original.jpg
  src/DayzMapsLoader.Core.Tests.xUnit/Core/TestData/MapMerge/png/0,0.png
  src/DayzMapsLoader.Core.Tests.xUnit/Core/TestData/MapMerge/png/0,1.png
  src/DayzMapsLoader.Core.Tests.xUnit/Core/TestData/MapMerge/png/1,0.png
  src/DayzMapsLoader.Core.Tests.xUnit/Core/TestData/MapMerge/png/1,1.png
  src/DayzMapsLoader.Core.Tests.xUnit/Core/TestData/MapMerge/png/Original.png
  src/DayzMapsLoader.Core.Tests.xUnit/Core/TestData/MapMerge/webp/0,0.webp
  src/DayzMapsLoader.Core.Tests.xUnit/Core/TestData/MapMerge/webp/0,1.webp
  src/DayzMapsLoader.Core.Tests.xUnit/Core/TestData/MapMerge/webp/1,0.webp
  src/DayzMapsLoader.Core.Tests.xUnit/Core/TestData/MapMerge/webp/1,1.webp
  src/DayzMapsLoader.Core.Tests.xUnit/Core/TestData/MapMerge/webp/Original.webp
  src/DayzMapsLoader.Core.Tests.xUnit/DayzMapsLoader.Core.Tests.xUnit.csproj
  src/DayzMapsLoader.Core.Tests.xUnit/DayzMapsLoader.Tests.xUnit.csproj
  src/DayzMapsLoader.Core.Tests.xUnit/Usings.cs
  src/DayzMapsLoader.Core/Contracts/Infrastructure/Repositories/IBaseRepository.cs
  src/DayzMapsLoader.Core/Contracts/Infrastructure/Repositories/IMapProvidersRepository.cs
  src/DayzMapsLoader.Core/Contracts/Infrastructure/Repositories/IMapsRepository.cs
  src/DayzMapsLoader.Core/Contracts/Infrastructure/Repositories/IProvidedMapsRepository.cs
  src/DayzMapsLoader.Core/DayzMapsLoader.Core.csproj
  src/DayzMapsLoader.Core/Features/MapArchive/Queries/GetMapImageArchive.cs
  src/DayzMapsLoader.Core/Features/MapProviders/Queries/GetMapProviders.cs
  src/DayzMapsLoader.Core/Features/ProvidedMaps/Queries/GetProvidedMapsByDetails.cs
  src/DayzMapsLoader.Core/Features/ProvidedMaps/Queries/GetProvidedMapsByMapId.cs
  src/DayzMapsLoader.Core/Properties/AssemblyInfo.cs
  src/DayzMapsLoader.Core/Services/MapMergeService.cs
  src/DayzMapsLoader.DependencyInjection/ServiceCollectionExtensions.cs
  src/DayzMapsLoader.Infrastructure/DayzMapsLoader.Infrastructure.csproj
  src/DayzMapsLoader.Infrastructure/Extensions/ServiceCollectionExtensions.cs
  src/DayzMapsLoader.Infrastructure/Migrations/DayzMapLoaderContextModelSnapshot.cs
  src/DayzMapsLoader.Presentation.WebApi/Properties/appsettings.Development.json
  src/DayzMapsLoader.Presentation.WebApi/Startup.cs
  src/DayzMapsLoader.Presentation.WebApi/appsettings.json
  src/DayzMapsLoader.Presentation.Wpf/App.xaml.cs
  src/DayzMapsLoader.Presentation.Wpf/DayzMapsLoader.Presentation.Wpf.csproj
  src/DayzMapsLoader.Presentation.Wpf/ViewModels/ContentGridMapDetailViewModel.cs
  src/DayzMapsLoader.Presentation.Wpf/Views/ContentGridMapDetailPage.xaml
  src/DayzMapsLoader.Presentation.Wpf/Views/ShellWindow.xaml
  src/DayzMapsLoader.sln
Labels: bug, refactoring, architecture, infrastructure, core, solution, tests

#91 Rename Tests project folder. Track appsettings.json files.
  .gitignore
  src/DayzMapsLoader.Infrastructure/Properties/appsettings.json
  src/DayzMapsLoader.Presentation.WebApi/Properties/appsettings.json
  src/DayzMapsLoader.Presentation.Wpf/Properties/appsettings.json
  src/DayzMapsLoader.Tests.xUnit/Core/FeaturesTests/MapArchive/Queries/GetAllMapsImagesArchiveTests.cs
  src/DayzMapsLoader.Tests.xUnit/Core/FeaturesTests/MapArchive/Queries/GetMapImageArchiveTest.cs
  src/DayzMapsLoader.Tests.xUnit/Core/FeaturesTests/MapArchive/Queries/GetMapImagePartsArchiveTests.cs
  src/DayzMapsLoader.Tests.xUnit/Core/FeaturesTests/MapProviders/Queries/GetMapProvidersTests.cs
  src/DayzMapsLoader.Tests.xUnit/Core/FeaturesTests/Maps/Queries/GetMapsTests.cs
  src/DayzMapsLoader.Tests.xUnit/Core/FeaturesTests/ProvidedMaps/Queries/GetProvidedMapsByDetailsTests.cs
  src/DayzMapsLoader.Tests.xUnit/Core/FeaturesTests/ProvidedMaps/Queries/GetProvidedMapsByMapIdTests.cs
  src/DayzMapsLoader.Tests.xUnit/Core/FeaturesTests/ProvidedMaps/Queries/GetProvidedMapsByProviderIdTests.cs
  src/DayzMapsLoader.Tests.xUnit/Core/FeaturesTests/ProvidedMaps/Queries/GetProvidedMapsTests.cs
  src/DayzMapsLoader.Tests.xUnit/Core/ServicesTests/MapDownloadArchiveServiceTests.cs
  src/DayzMapsLoader.Tests.xUnit/Core/ServicesTests/MapDownloadImageServiceTests.cs
  src/DayzMapsLoader.Tests.xUnit/Core/ServicesTests/MapMergeServiceTests.cs
  src/DayzMapsLoader.Tests.xUnit/Core/TestData/MapDownload/DataGenerator.cs
  src/DayzMapsLoader.Tests.xUnit/Core/TestData/MapMerge/jpg/0,0.jpg
  src/DayzMapsLoader.Tests.xUnit/Core/TestData/MapMerge/jpg/0,1.jpg
  src/DayzMapsLoader.Tests.xUnit/Core/TestData/MapMerge/jpg/1,0.jpg
  src/DayzMapsLoader.Tests.xUnit/Core/TestData/MapMerge/jpg/1,1.jpg
  src/DayzMapsLoader.Tests.xUnit/Core/TestData/MapMerge/jpg/Original.jpg
  src/DayzMapsLoader.Tests.xUnit/Core/TestData/MapMerge/png/0,0.png
  src/DayzMapsLoader.Tests.xUnit/Core/TestData/MapMerge/png/0,1.png
  src/DayzMapsLoader.Tests.xUnit/Core/TestData/MapMerge/png/1,0.png
  src/DayzMapsLoader.Tests.xUnit/Core/TestData/MapMerge/png/1,1.png
  src/DayzMapsLoader.Tests.xUnit/Core/TestData/MapMerge/png/Original.png
  src/DayzMapsLoader.Tests.xUnit/Core/TestData/MapMerge/webp/0,0.webp
  src/DayzMapsLoader.Tests.xUnit/Core/TestData/MapMerge/webp/0,1.webp
  src/DayzMapsLoader.Tests.xUnit/Core/TestData/MapMerge/webp/1,0.webp
  src/DayzMapsLoader.Tests.xUnit/Core/TestData/MapMerge/webp/1,1.webp
  src/DayzMapsLoader.Tests.xUnit/Core/TestData/MapMerge/webp/Original.webp
  src/DayzMapsLoader.Tests.xUnit/DayzMapsLoader.Tests.xUnit.csproj
  src/DayzMapsLoader.Tests.xUnit/Usings.cs
  src/DayzMapsLoader.sln
Labels: solution

#96 Add method for an update database. Change work flow with config files.
  src/DayzMapsLoader.DependencyInjection/ServiceCollectionExtensions.cs
  src/DayzMapsLoader.Infrastructure/DayzMapsLoader.Infrastructure.csproj
  src/DayzMapsLoader.Infrastructure/Extensions/ServiceCollectionExtensions.cs
  src/DayzMapsLoader.Infrastructure/Properties/appsettings.json
  src/DayzMapsLoader.Presentation.WebApi/Properties/appsettings.json
  src/DayzMapsLoader.Presentation.Wpf/App.xaml.cs
  src/DayzMapsLoader.Presentation.Wpf/Properties/appsettings.json
Labels: infrastructure, wpf, solution, web api

#97 Deleted unused dependencies. Update nuget packages.
  src/DayzMapsLoader.Core/DayzMapsLoader.Core.csproj
  src/DayzMapsLoader.DependencyInjection/DayzMapsLoader.DependencyInjection.csproj
  src/DayzMapsLoader.Infrastructure/DayzMapsLoader.Infrastructure.csproj
  src/DayzMapsLoader.Infrastructure/Extensions/ServiceCollectionExtensions.cs
  src/DayzMapsLoader.Presentation.WebApi/DayzMapsLoader.Presentation.WebApi.csproj
  src/DayzMapsLoader.Presentation.WebApi/Properties/appsettings.Development.json
  src/DayzMapsLoader.Presentation.Wpf/App.xaml.cs
  src/DayzMapsLoader.Presentation.Wpf/DayzMapsLoader.Presentation.Wpf.csproj
  src/DayzMapsLoader.Tests.xUnit/DayzMapsLoader.Tests.xUnit.csproj
  src/DayzMapsLoader.Tests.xUnit/Properties/appsettings.json
Labels: refactoring, solution

#102 Delete DependencyInjection project
  src/DayzMapsLoader.DependencyInjection/DayzMapsLoader.DependencyInjection.csproj
  src/DayzMapsLoader.DependencyInjection/ServiceCollectionExtensions.cs
  src/DayzMapsLoader.Infrastructure/Extensions/ServiceCollectionExtensions.cs
  src/DayzMapsLoader.Presentation.WebApi/DayzMapsLoader.Presentation.WebApi.csproj
  src/DayzMapsLoader.Presentation.WebApi/Program.cs
  src/DayzMapsLoader.Presentation.WebApi/Properties/appsettings.json
  src/DayzMapsLoader.Presentation.WebApi/Startup.cs
  src/DayzMapsLoader.Presentation.Wpf/App.xaml.cs
  src/DayzMapsLoader.Presentation.Wpf/DayzMapsLoader.Presentation.Wpf.csproj
  src/DayzMapsLoader.Presentation.Wpf/Properties/appsettings.json
  src/DayzMapsLoader.Tests.xUnit/Core/ServicesTests/MapDownloadArchiveServiceTests.cs
  src/DayzMapsLoader.Tests.xUnit/Core/ServicesTests/MapDownloadImageServiceTests.cs
  src/DayzMapsLoader.Tests.xUnit/Core/ServicesTests/MapMergeServiceTests.cs
  src/DayzMapsLoader.Tests.xUnit/DayzMapsLoader.Tests.xUnit.csproj
  src/DayzMapsLoader.Tests.xUnit/Extensions/ServiceCollectionExtensions.cs
  src/DayzMapsLoader.sln
Labels: architecture, solution

#105 104: Delete shared project. Move files in Core project.
  src/DayzMapsLoader.Core/Constants/MapImageConstants.cs
  src/DayzMapsLoader.Core/Contracts/Infrastructure/Services/IMultipleThirdPartyApiService.cs
  src/DayzMapsLoader.Core/Contracts/Services/IMapMergeService.cs
  src/DayzMapsLoader.Core/DayzMapsLoader.Core.csproj
  src/DayzMapsLoader.Core/Enums/ImageExtension.cs
  src/DayzMapsLoader.Core/Models/MapPart.cs
  src/DayzMapsLoader.Core/Models/MapParts.cs
  src/DayzMapsLoader.Core/Models/MapSize.cs
  src/DayzMapsLoader.Core/Services/BaseMapDownloadService.cs
  src/DayzMapsLoader.Core/Services/MapMergeService.cs
  src/DayzMapsLoader.Infrastructure/Services/MultipleThirdPartyApiService.cs
  src/DayzMapsLoader.Shared/DayzMapsLoader.Shared.csproj
  src/DayzMapsLoader.Tests.xUnit/Core/ServicesTests/MapDownloadArchiveServiceTests.cs
  src/DayzMapsLoader.Tests.xUnit/Core/ServicesTests/MapMergeServiceTests.cs
  src/DayzMapsLoader.sln
Labels: architecture

#98 88 web api refactoring
  .gitignore
  src/DayzMapsLoader.Core/Contracts/Infrastructure/Repositories/IProvidedMapsRepository.cs
  src/DayzMapsLoader.Core/DayzMapsLoader.Core.csproj
  src/DayzMapsLoader.Core/Features/Maps/Queries/GetMapsByProviderId.cs
  src/DayzMapsLoader.Infrastructure/Properties/appsettings.json
  src/DayzMapsLoader.Infrastructure/Repositories/BaseRepository.cs
  src/DayzMapsLoader.Infrastructure/Repositories/ProvidedMapsRepository.cs
  src/DayzMapsLoader.Presentation.WebApi/Controllers/MapProvidersController.cs
  src/DayzMapsLoader.Presentation.WebApi/Controllers/MapsController.cs
  src/DayzMapsLoader.Presentation.WebApi/Controllers/ProvidedMapsController.cs
  src/DayzMapsLoader.Tests.xUnit/Core/FeaturesTests/Maps/Queries/GetMapsTests.cs
Labels: enhancement, refactoring, infrastructure, core, web api
